### PR TITLE
Add models (old)

### PR DESCRIPTION
**Pull request by dinoocch**
This commit adds the basic models required for the application, in the
future, these models may change. However the general structure will
remain the same.

### CODE REVIEW

**Comment by dinoocch** [comment]
Fails due to migration file line length

**Comment by dinoocch** [comment]
For the future, we may wish to switch to JSONField on those elements that represent dynamic data (choices, etc)...Per https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#jsonfield

This offers likely the cheapest and easiest performance, and will likely have near the performance of a true model/table.  Unfortunately this is a postgresql only feature, and our test instance uses sqlite...

It is also an option to convert our forms and submissions to this - since the impact is minimal and it may make things a bit easier (and it will certainly make things easier to conceptualize/handle the various widgets). Just throwing it out there 😸 

I probably need an answer on this before I get too far though.

**Comment by the-maldridge** [comment]
@dinoocch we can switch the tests to use PostgreSQL if that would help.  It is somewhat annoying to constrain the available databases on this, but if it offers a substantial benefit we can switch to it.

**Comment by dinoocch** [comment]
It pretty much completely flattens the database, if we want it to...ie, suddenly we can have just a form and a formSubmission, instead of having tons of various widgets. It hardlocks us to postgresql though. I'm open to either option really.

**Pull request closed without merging**
